### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [mikeqfu/pyrcs#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.2.6. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary pyrcs -w /tmp/ext pyrcs==0.2.6
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting pyrcs==0.2.6
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/fad/d9423f9b11cdd/pyrcs-0.2.6.tar.gz (41 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-5d39cnf_/pyrcs/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-5d39cnf_/pyrcs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-5d39cnf_/pyrcs/pip-egg-info
         cwd: /tmp/pip-wheel-5d39cnf_/pyrcs/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-5d39cnf_/pyrcs/setup.py", line 22, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by mikeqfu** [comment]
@thatch I think the issue has been sorted. Can you try it again and let me know if it works now?
