### ISSUE TITLE
Documentation build on Read the Docs failed

### ISSUE THREAD

**Issue by mikeqfu** [mikeqfu/pyrcs#20]
Error message:

> Configuration error:
> There is a programmable error in your configuration file:
> 
> Traceback (most recent call last):
>   File "/home/docs/checkouts/readthedocs.org/user_builds/pyrcs/envs/latest/lib/python3.9/site-packages/sphinx/config.py", line 529, in eval_config_file
>     exec(code, namespace)  # NoQA: S102
>   File "/home/docs/checkouts/readthedocs.org/user_builds/pyrcs/checkouts/latest/docs/source/conf.py", line 195, in <module>
>     affil_dept, affil_sch, affil_univ = __affiliation__.split(', ')
> ValueError: not enough values to unpack (expected 3, got 2)

**Comment by mikeqfu** [comment]
**Following-up issue:**

_Error
We encountered a problem with a command while building your project. To resolve this error, double check your project configuration and installed dependencies are correct and have not changed recently._

> Collecting beautifulsoup4 (from -r docs/source/rtd-req.txt (line 1))
>   Downloading beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
> ERROR: Ignored the following yanked versions: 1.0.16, 1.0.17, 1.0.19, 1.0.20, 1.0.21, 1.0.22, 1.0.24, 1.0.25, 1.0.26, 1.1.0, 1.1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.9, 1.2.10, 1.2.11, 1.2.12, 1.2.13, 1.2.14, 1.2.15, 1.2.16, 1.2.17, 1.2.18, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4.0, 1.4.1
> ERROR: Ignored the following versions that require a different python version: 2.0.0 Requires-Python >=3.10
> ERROR: Could not find a version that satisfies the requirement pyhelpers>=2.0.0 (from versions: 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.5.0, 1.5.1, 1.5.2)
> ERROR: No matching distribution found for pyhelpers>=2.0.0
